"""Renamed column link to upload

Revision ID: 0410b61c3b49
Revises: 228cd81ec1a5
Create Date: 2024-04-10 06:52:52.964135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0410b61c3b49'
down_revision = '228cd81ec1a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hackathons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload', sa.String(length=100), nullable=True))
        batch_op.drop_column('link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hackathons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('upload')

    # ### end Alembic commands ###
