"""Compressed into one table

Revision ID: 228cd81ec1a5
Revises: e50f9a1cc9c2
Create Date: 2024-04-10 06:42:51.162526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '228cd81ec1a5'
down_revision = 'e50f9a1cc9c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hackathons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('link', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hackathons', schema=None) as batch_op:
        batch_op.drop_column('link')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
