"""Add initial tables

Revision ID: e50f9a1cc9c2
Revises:
Create Date: 2024-04-10 01:45:32.848446

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e50f9a1cc9c2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hackathons",
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("registration_end", sa.TIMESTAMP(), nullable=True),
        sa.Column("date_from", sa.TIMESTAMP(), nullable=True),
        sa.Column("date_end", sa.TIMESTAMP(), nullable=True),
        sa.Column("prize_pool", sa.FLOAT(), nullable=True),
        sa.Column("tags", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "banners",
        sa.Column("hackathon_id", sa.Integer(), nullable=False),
        sa.Column("link", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hackathon_id"],
            ["hackathons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "contents",
        sa.Column("hackathon_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hackathon_id"],
            ["hackathons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contents")
    op.drop_table("banners")
    op.drop_table("hackathons")
    # ### end Alembic commands ###
